ll

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -3,59 +3,212 @@ on:
   push:
     branches:
       - master
+      - develop
   pull_request:
     branches:
       - master
+      - develop
+
 jobs:
-  build:
-    name: Autograding
+  build-loyalty:
+    name: build loyalty
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-
-      - uses: docker/setup-buildx-action@v2
-
-      # TODO build and run unit tests
-
-      - name: Build images
-        timeout-minutes: 10
-        run: docker compose build
-
-      - name: Run containers
-        timeout-minutes: 5
+      - name: build tests
         run: |
+          docker build -t loyalty:latest -f ./loyalty.dockerfile . --target=build
+          docker save loyalty:latest > loyalty_build.tar
+      - name: build backend
+        run: |
+          docker build -t loaylty:latest -f ./loyalty.dockerfile . --target=release
+          docker save loyalty:latest > loyalty_release.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: tests-loyalty-artefact 
+          path: loyalty_build.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: backend-loyalty-artefact 
+          path: loyalty_release.tar
+
+  build-payment:
+    name: build payment
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: build tests
+        run: |
+          docker build -t payment:latest -f ./payment.dockerfile . --target=build
+          docker save payment:latest > payment_build.tar
+      - name: build backend
+        run: |
+          docker build -t payment:latest -f ./payment.dockerfile . --target=release
+          docker save payment:latest > payment_release.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: tests-payment-artefact 
+          path: payment_build.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: backend-payment-artefact 
+          path: payment_release.tar
+
+  build-reservation:
+    name: build reservation
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: build tests
+        run: |
+          docker build -t reservation:latest -f ./reservation.dockerfile . --target=build
+          docker save reservation:latest > reservation_build.tar
+      - name: build backend
+        run: |
+          docker build -t reservation:latest -f ./reservation.dockerfile . --target=release
+          docker save reservation:latest > reservation_release.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: tests-reservation-artefact 
+          path: reservation_build.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: backend-reservation-artefact 
+          path: reservation_release.tar
+
+  build-gateway:
+    name: build gateway
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: build backend
+        run: |
+          docker build -t gateway:latest -f ./gateway.dockerfile . --target=release
+          docker save gateway:latest > gateway_release.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: backend-gateway-artefact 
+          path: gateway_release.tar
+
+  test-loyalty:
+    name: test loyalty
+    runs-on: ubuntu-latest
+    needs: build-loyalty
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: tests-loyalty-artefact 
+      - name: run tests
+        run: |
+          docker load < loyalty_build.tar
+          docker compose -f ./docker-compose.tests.yml up loyalty_tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
+
+  test-payment:
+    name: test payment
+    runs-on: ubuntu-latest
+    needs: build-payment
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: tests-payment-artefact 
+      - name: run tests
+        run: |
+          docker load < payment_build.tar
+          docker compose -f ./docker-compose.tests.yml up payment_tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
+
+  test-reservation:
+    name: test reservation
+    runs-on: ubuntu-latest
+    needs: build-reservation
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: tests-reservation-artefact 
+      - name: run tests
+        run: |
+          docker load < reservation_build.tar
+          docker compose -f ./docker-compose.tests.yml up reservation_tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
+
+  integration-tests:
+    name: intergation tests
+    runs-on: ubuntu-latest
+    needs: [build-gateway, test-loyalty, test-payment, test-reservation]
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/download-artifact@v4
+        with: 
+          name: backend-loyalty-artefact 
+      - uses: actions/download-artifact@v4
+        with: 
+          name: backend-payment-artefact 
+      - uses: actions/download-artifact@v4
+        with: 
+          name: backend-reservation-artefact 
+      - uses: actions/download-artifact@v4
+        with: 
+          name: backend-gateway-artefact 
+      - name: Run
+        run: |
+          docker load < loyalty_release.tar
+          rm loyalty_release.tar
+          docker load < payment_release.tar
+          rm payment_release.tar
+          docker load < reservation_release.tar
+          rm reservation_release.tar
+          docker load < gateway_release.tar
+          rm gateway_release.tar
           docker compose up -d
-          ./scripts/wait-script.sh
-        env:
-          WAIT_PORTS: 8080,8070,8060,8050
-
-      # TODO setup variant, service and port
-
+          sleep 10
+      - uses: docker/setup-buildx-action@v2
       - name: Run API Tests
         timeout-minutes: 5
         run: ./scripts/test-script.sh
         env:
-          VARIANT: <variant>
-          SERVICE_NAME: <your service name>
-          PORT_NUMBER: <port number>
-
+          VARIANT: v2
+          SERVICE_NAME: loyalty_service
+          PORT_NUMBER: 8080
       - uses: education/autograding@v1
         id: autograder
         continue-on-error: true
-
-      - name: Github auto grader mark
-        uses: Romanow/google-sheet-autograder-marker@v1.0
-        with:
-          google_token: ${{secrets.GOOGLE_API_KEY}}
-          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
-          homework_number: 3
-          user_column: 'D'
-          column_offset: 'F'
-          mark: "'+"
-
       - name: Stop containers
-        if: always()
-        continue-on-error: true
-        run: docker compose down -v
+        run: docker compose down
